# Generated by Django 5.2.17 on 2026-09-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('job_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('importance', models.CharField(choices=[('Required', 'Required'), ('Preferred', 'Preferred')], max_length=20)),
                ('min_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'db_table': 'job_skills',
            },
        ),
    ]
