# Generated by Django 5.2.17 on 2026-09-12 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('aliases', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('candidate_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('proficiency', models.CharField(blank=True, max_length=50, null=True)),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('evidence_text', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'db_table': 'candidate_skills',
                'constraints': [models.UniqueConstraint(fields=('candidate', 'skill'), name='unique_candidate_skill')],
            },
        ),
    ]
