# Generated by Django 5.2.17 on 2026-09-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_jobskill'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('semantic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('experience_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('education_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skill_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resume_quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
            ],
            options={
                'db_table': 'resume_analysis',
            },
        ),
    ]
