# Generated by Django 5.2.17 on 2026-09-12 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('gap_id', models.AutoField(primary_key=True, serialize=False)),
                ('gap_type', models.CharField(choices=[('Missing', 'Missing'), ('Partial', 'Partial')], max_length=20)),
                ('candidate_level', models.CharField(blank=True, max_length=50, null=True)),
                ('required_level', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True)),
                ('analysis', models.ForeignKey(db_column='analysis_id', on_delete=django.db.models.deletion.CASCADE, to='analysis.resumeanalysis')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'db_table': 'skill_gaps',
            },
        ),
    ]
