# Generated by Django 5.2.17 on 2026-09-12 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_skillgap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateScore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('experience_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('education_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('semantic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resume_quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('scoring_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(db_column='analysis_id', on_delete=django.db.models.deletion.CASCADE, to='analysis.resumeanalysis')),
            ],
            options={
                'db_table': 'candidate_scores',
            },
        ),
    ]
