# Generated by Django 5.2.17 on 2026-09-12 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_candidatescore'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('Technical', 'Technical'), ('Behavioral', 'Behavioral'), ('Experience', 'Experience'), ('Skill Gap', 'Skill Gap')], max_length=20)),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('generated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(db_column='analysis_id', on_delete=django.db.models.deletion.CASCADE, to='analysis.resumeanalysis')),
                ('related_skill', models.ForeignKey(blank=True, db_column='related_skill_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.skill')),
            ],
            options={
                'db_table': 'interview_questions',
            },
        ),
    ]
