# Generated by Django 5.2.17 on 2026-09-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_interviewsession'),
        ('jobs', '0002_jobskill'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resumeanalysis',
            constraint=models.UniqueConstraint(fields=('resume', 'job'), name='unique_resume_job_analysis'),
        ),
    ]
